version: '3.3'
services:
    minecraft-server:
        volumes:
            - './minecraft-data:/data'
        environment:
            - VERSION=1.20.2
            - TYPE=FABRIC
            - TZ=Asia/Shanghai
            - INIT_MEMORY=1G
            - MAX_MEMORY=3g
            - ONLINE_MODE=TRUE
            - MODE=Survival
            - MOTD=欢迎来到星辰服务器
            - EULA=TRUE
        ports:
            - '25565:25565'
        container_name: minecraft-server
        image: itzg/minecraft-server
